import { MAIN_ROUTES, PROJECT, getRecordCountBreakdown, getRecordCounts, getRegistryV3Summary } from '../lib/machine-readable';

export function GET() {
  const counts = getRecordCounts();
  const breakdown = getRecordCountBreakdown();
  const registryV3 = getRegistryV3Summary();
  const body = [
    '# Stable or Gone',
    '',
    PROJECT.description,
    '',
    `Canonical site: ${PROJECT.canonicalOrigin}/`,
    '',
    'Machine-readable files:',
    '- /version.json',
    '- /data/manifest.json',
    '- /data/stablecoin/{slug}.json',
    '- /data/stats.json',
    '- /data/stats-history.json',
    '- /ai.txt',
    '',
    'Per-record data:',
    '- /data/stablecoin/{slug}.json is a deterministic canonical-only dossier for the same record as /stablecoin/{slug}/.',
    '- Each dossier preserves canonical identity/current state and related reviewed organizations, relationships, events, evidence, reserve reports, known unknowns, regulatory notes, deployments, and available v3 profile records.',
    '- Typed event details preserve recorded depeg recovery, regulatory, redemption-change, migration, and other lifecycle semantics without inferring missing outcomes.',
    '',
    'Main routes:',
    ...MAIN_ROUTES.map((route) => `- ${route}`),
    '',
    'Build-time record counts:',
    `- Stablecoins: ${counts.primary_records}`,
    `- Organizations: ${breakdown.organizations}`,
    `- Relationships: ${breakdown.relationships}`,
    `- Events: ${counts.events}`,
    `- Evidence records: ${counts.evidence}`,
    `- Reserve reports: ${breakdown.reserve_reports}`,
    `- Known unknowns: ${breakdown.known_unknowns}`,
    `- Deployments: ${breakdown.deployments}`,
    '',
    'Registry v3 additive layers:',
    `- Protected stable assets: ${registryV3.protected_stable_assets}`,
    `- Legal profiles: ${registryV3.record_counts.legal_profiles}`,
    `- Stable-asset relationships: ${registryV3.record_counts.stable_asset_relationships}`,
    `- Reserve components: ${registryV3.record_counts.reserve_components}`,
    `- Income profiles: ${registryV3.record_counts.income_profiles}`,
    `- Deployment view rows: ${registryV3.record_counts.deployments}`,
    '',
    'Statistics notes:',
    '- /data/stats.json is deterministic derived output from reviewed canonical registry inputs.',
    '- /data/stats-history.json contains reviewed append-only checkpoint snapshots, not every deployment build.',
    '- Statistics preserve unknown states and exclude live price, market cap, APY, safety scores, and risk scores.',
    '',
    'Use notes:',
    '- This is historical reference material, not live market data.',
    '- This is not legal, tax, investment, wallet, issuer, or redemption support.',
    '- Evidence is scoped to the stablecoin, organization, event, and claim it supports.',
    '- Use methodology, event details, evidence tables, reserve reports, and known-unknown records when interpreting entries.',
    '- Public machine-readable files contain reviewed public registry information only.',
    '- Registry v3 layers are additive to the existing v2 public contract during the parity phase.',
    '- Record data may be incomplete or revised.',
    '',
  ].join('\n');

  return new Response(body, {
    headers: {
      'content-type': 'text/plain; charset=utf-8',
      'cache-control': 'public, max-age=3600, must-revalidate',
    },
  });
}