export type DeploymentTaxonomyEntry = { value: string; public_label: string; sort_order: number };
export const publicDeploymentCategories: DeploymentTaxonomyEntry[];
export const deploymentTypeCategoryMap: Record<string, string>;
export const deploymentOperationalStates: DeploymentTaxonomyEntry[];
export const rawDeploymentStatusOperationalMap: Record<string, string>;
export const deploymentChangeStates: DeploymentTaxonomyEntry[];
export const rawDeploymentStatusChangeMap: Record<string, string>;
export const deploymentCanonicalityLabels: Record<string, string>;
export const deploymentCanonicalityRecordStates: DeploymentTaxonomyEntry[];
export const deploymentVerificationStates: DeploymentTaxonomyEntry[];
export const contractIdentityStates: DeploymentTaxonomyEntry[];
export const networkIdentityStates: DeploymentTaxonomyEntry[];
export function getPublicDeploymentCategory(deploymentType?: string | null): string;
export function getPublicDeploymentCategoryLabel(value?: string | null): string;
export function getDeploymentOperationalState(rawStatus?: string | null): string;
export function getDeploymentOperationalStateLabel(value?: string | null): string;
export function getDeploymentChangeState(rawStatus?: string | null): string;
export function getDeploymentChangeStateLabel(value?: string | null): string;
export function getDeploymentCanonicalityLabel(value?: string | null): string;
export function getDeploymentCanonicalityRecordState(canonicality?: string | null): string;
export function getDeploymentCanonicalityRecordStateLabel(value?: string | null): string;
export function getContractIdentityState(contractAddress?: string | null): string;
export function getContractIdentityStateLabel(value?: string | null): string;
export function getNetworkIdentityState(chain?: string | null): string;
export function getNetworkIdentityStateLabel(value?: string | null): string;
export function getDeploymentVerificationState(deployment?: { verification_status?: string | null; contract_address?: string | null; evidence_ids?: string[] | null } | null): string;
export function getDeploymentVerificationStateLabel(value?: string | null): string;
