const LOGOS_BY_SLUG: Readonly<Record<string, string>> = {
  'acala-ausd': '/stablecoin-logos/acala-ausd.png',
  'ae-coin': '/stablecoin-logos/ae-coin.png',
  'agora-ausd': '/stablecoin-logos/agora-ausd.png',
  'agoric-ist': '/stablecoin-logos/ist.svg',
  'alusd': '/stablecoin-logos/alusd.svg',
  'anzen-usdz': '/stablecoin-logos/anzen-usdz.png',
  'audd': '/stablecoin-logos/audd.png',
  'avalon-usda': '/stablecoin-logos/avalon-usda.png',
  'basis-cash': '/stablecoin-logos/basis-cash.png',
  'beanstalk-bean': '/stablecoin-logos/beanstalk-bean.svg',
  'berachain-honey': '/stablecoin-logos/berachain-honey.svg',
  'blast-usdb': '/stablecoin-logos/blast-usdb.png',
  'bold': '/stablecoin-logos/bold.svg',
  'brz': '/stablecoin-logos/brz.png',
  'busd': '/stablecoin-logos/busd.png',
  'cashio-dollar': '/stablecoin-logos/cashio-dollar.png',
  'chfau': '/stablecoin-logos/chfau.png',
  'coins-phpc': '/stablecoin-logos/coins-phpc.png',
  'crvusd': '/stablecoin-logos/crvusd.svg',
  'dai': '/stablecoin-logos/dai.svg',
  'dforce-usx': '/stablecoin-logos/dforce-usx.svg',
  'djed': '/stablecoin-logos/djed.svg',
  'dola': '/stablecoin-logos/dola.svg',
  'dollar-on-chain': '/stablecoin-logos/dollar-on-chain.svg',
  'dynamic-set-dollar': '/stablecoin-logos/dynamic-set-dollar.png',
  'empty-set-dollar': '/stablecoin-logos/empty-set-dollar.png',
  'eura': '/stablecoin-logos/eura.svg',
  'eurau': '/stablecoin-logos/eurau.png',
  'eurc': '/stablecoin-logos/eurc.svg',
  'eurcv': '/stablecoin-logos/eurcv.svg',
  'euri': '/stablecoin-logos/euri.png',
  'eurq': '/stablecoin-logos/eurq.svg',
  'eurs': '/stablecoin-logos/eurs.svg',
  'eurt': '/stablecoin-logos/eurt.svg',
  'falcon-usdf': '/stablecoin-logos/falcon-usdf.png',
  'fdusd': '/stablecoin-logos/fdusd.svg',
  'fei': '/stablecoin-logos/fei.svg',
  'frax': '/stablecoin-logos/frax.svg',
  'fx-protocol-fxusd': '/stablecoin-logos/fx-protocol-fxusd.png',
  'gbpq': '/stablecoin-logos/gbpq.png',
  'gho': '/stablecoin-logos/gho.svg',
  'gusd': '/stablecoin-logos/gusd.svg',
  'gyen': '/stablecoin-logos/gyen.svg',
  'gyroscope-gyd': '/stablecoin-logos/gyroscope-gyd.svg',
  'husd': '/stablecoin-logos/husd.svg',
  'iron': '/stablecoin-logos/iron.svg',
  'jpyc': '/stablecoin-logos/jpyc.png',
  'jpysc': '/stablecoin-logos/jpysc.svg',
  'kava-usdx': '/stablecoin-logos/kava-usdx.svg',
  'lisusd': '/stablecoin-logos/lisusd.png',
  'loon-cadc': '/stablecoin-logos/loon-cadc.png',
  'lusd': '/stablecoin-logos/lusd.svg',
  'm0-m': '/stablecoin-logos/m0-m.png',
  'mainstreet-msusd': '/stablecoin-logos/mainstreet-msusd.png',
  'mento-dollar': '/stablecoin-logos/mento-dollar.png',
  'mento-eurm': '/stablecoin-logos/mento-eurm.svg',
  'mim': '/stablecoin-logos/mim.svg',
  'monerium-eure': '/stablecoin-logos/monerium-eure.svg',
  'mountain-usdm': '/stablecoin-logos/mountain-usdm.svg',
  'musd': '/stablecoin-logos/musd.svg',
  'near-usn': '/stablecoin-logos/near-usn.svg',
  'noble-usdn': '/stablecoin-logos/noble-usdn.png',
  'nuon': '/stablecoin-logos/nuon.png',
  'nzds': '/stablecoin-logos/nzds.svg',
  'origin-dollar': '/stablecoin-logos/ousd.svg',
  'paxg': '/stablecoin-logos/paxg.svg',
  'plnq': '/stablecoin-logos/plnq.png',
  'poundtoken': '/stablecoin-logos/poundtoken.png',
  'pyusd': '/stablecoin-logos/pyusd.svg',
  'qidao-mai': '/stablecoin-logos/qidao-mai.png',
  'rai': '/stablecoin-logos/rai.svg',
  'reserve-usd3': '/stablecoin-logos/reserve-usd3.png',
  'rlusd': '/stablecoin-logos/rlusd.svg',
  'sai': '/stablecoin-logos/sai.svg',
  'sdai': '/stablecoin-logos/sdai.png',
  'sekau': '/stablecoin-logos/sekau.png',
  'sofiusd': '/stablecoin-logos/sofiusd.svg',
  'solstice-usx': '/stablecoin-logos/solstice-usx.png',
  'spot': '/stablecoin-logos/spot.png',
  'stables-labs-usdx': '/stablecoin-logos/stables-labs-usdx.png',
  'stablr-eurr': '/stablecoin-logos/stablr-eurr.png',
  'stablr-usdr': '/stablecoin-logos/stablr-usdr.png',
  'straitsx-usd-xusd': '/stablecoin-logos/straitsx-usd-xusd.svg',
  'straitsx-xidr': '/stablecoin-logos/straitsx-xidr.svg',
  'susd': '/stablecoin-logos/susd.svg',
  'susde': '/stablecoin-logos/susde.svg',
  'susds': '/stablecoin-logos/susds.svg',
  'tryb': '/stablecoin-logos/tryb.svg',
  'tusd': '/stablecoin-logos/tusd.svg',
  'united-stables-u': '/stablecoin-logos/united-stables-u.svg',
  'usat': '/stablecoin-logos/usat.png',
  'usd0': '/stablecoin-logos/usd0.png',
  'usd1': '/stablecoin-logos/usd1.png',
  'usdc': '/stablecoin-logos/usdc.svg',
  'usdd': '/stablecoin-logos/usdd.svg',
  'usde': '/stablecoin-logos/usde.svg',
  'usdg': '/stablecoin-logos/usdg.svg',
  'usdgo': '/stablecoin-logos/usdgo.png',
  'usdh': '/stablecoin-logos/usdh.png',
  'usdn': '/stablecoin-logos/usdn.png',
  'usdp': '/stablecoin-logos/pax.svg',
  'usdq': '/stablecoin-logos/usdq.svg',
  'usds': '/stablecoin-logos/usds.svg',
  'usdt': '/stablecoin-logos/usdt.svg',
  'usdtb': '/stablecoin-logos/usdtb.svg',
  'usdy': '/stablecoin-logos/usdy.svg',
  'usk': '/stablecoin-logos/usk.svg',
  'usr': '/stablecoin-logos/usr.svg',
  'ust': '/stablecoin-logos/ust.png',
  'usyc': '/stablecoin-logos/usyc.png',
  'uxd-protocol': '/stablecoin-logos/uxd-protocol.png',
  'vai': '/stablecoin-logos/vai.svg',
  'vchf': '/stablecoin-logos/vchf.png',
  'xaut': '/stablecoin-logos/xaut.svg',
  'xsgd': '/stablecoin-logos/xsgd.svg',
  'zarp': '/stablecoin-logos/zarp.svg'
};

// Symbol fallback is intentionally allow-listed. Ambiguous corpus symbols such as
// USX, USDX, and USDN must never resolve to a logo by symbol alone.
const LOGOS_BY_AUDITED_UNIQUE_SYMBOL: Readonly<Record<string, string>> = {
  'bean': LOGOS_BY_SLUG['beanstalk-bean'],
  'honey': LOGOS_BY_SLUG['berachain-honey'],
  'crvusd': LOGOS_BY_SLUG.crvusd,
  'dai': LOGOS_BY_SLUG.dai,
  'djed': LOGOS_BY_SLUG.djed,
  'dola': LOGOS_BY_SLUG.dola,
  'eurc': LOGOS_BY_SLUG.eurc,
  'eurs': LOGOS_BY_SLUG.eurs,
  'eurt': LOGOS_BY_SLUG.eurt,
  'fdusd': LOGOS_BY_SLUG.fdusd,
  'fei': LOGOS_BY_SLUG.fei,
  'frax': LOGOS_BY_SLUG.frax,
  'gho': LOGOS_BY_SLUG.gho,
  'gusd': LOGOS_BY_SLUG.gusd,
  'gyen': LOGOS_BY_SLUG.gyen,
  'husd': LOGOS_BY_SLUG.husd,
  'iron': LOGOS_BY_SLUG.iron,
  'ist': LOGOS_BY_SLUG['agoric-ist'],
  'lusd': LOGOS_BY_SLUG.lusd,
  'mim': LOGOS_BY_SLUG.mim,
  'musd': LOGOS_BY_SLUG.musd,
  'ousd': LOGOS_BY_SLUG['origin-dollar'],
  'paxg': LOGOS_BY_SLUG.paxg,
  'pyusd': LOGOS_BY_SLUG.pyusd,
  'rai': LOGOS_BY_SLUG.rai,
  'sai': LOGOS_BY_SLUG.sai,
  'susd': LOGOS_BY_SLUG.susd,
  'tryb': LOGOS_BY_SLUG.tryb,
  'tusd': LOGOS_BY_SLUG.tusd,
  'u': LOGOS_BY_SLUG['united-stables-u'],
  'usdc': LOGOS_BY_SLUG.usdc,
  'usdd': LOGOS_BY_SLUG.usdd,
  'usde': LOGOS_BY_SLUG.usde,
  'usdp': LOGOS_BY_SLUG.usdp,
  'usdt': LOGOS_BY_SLUG.usdt,
  'usn': LOGOS_BY_SLUG['near-usn'],
  'vai': LOGOS_BY_SLUG.vai,
  'xaut': LOGOS_BY_SLUG.xaut,
  'xsgd': LOGOS_BY_SLUG.xsgd
};

const normalizeLogoKey = (value?: string | null) => String(value ?? '').trim().toLowerCase();

export const LOCAL_STABLECOIN_LOGO_COUNT = Object.keys(LOGOS_BY_SLUG).length;

export const resolveStablecoinLogo = ({ slug, symbol }: { slug?: string | null; symbol?: string | null }) => {
  const slugKey = normalizeLogoKey(slug);
  const symbolKey = normalizeLogoKey(symbol);
  return LOGOS_BY_SLUG[slugKey] ?? LOGOS_BY_AUDITED_UNIQUE_SYMBOL[symbolKey] ?? null;
};

export const hasStablecoinLogo = (value: { slug?: string | null; symbol?: string | null }) => Boolean(resolveStablecoinLogo(value));
