import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();const dataDir=path.join(root,'data');const failures=[];
function read(file){try{const v=JSON.parse(fs.readFileSync(path.join(dataDir,file),'utf8'));if(!Array.isArray(v)){failures.push(`${file}: expected array`);return[]}return v.map((row)=>({...row,__source_file:file}))}catch(e){failures.push(`${file}: ${e.message}`);return[]}}
const combine=(...files)=>files.flatMap(read);const label=(row)=>`${row.__source_file??'unknown'}: ${row.id??row.slug??'unknown'}`;
function req(row,field){if(row[field]===undefined||row[field]===null||row[field]==='')failures.push(`${label(row)} missing ${field}`)}
function unique(name,rows,field){const seen=new Map();for(const row of rows){const v=row[field];if(!v)continue;if(seen.has(v))failures.push(`${name}: duplicate ${field} ${v} in ${seen.get(v)} and ${row.__source_file}`);else seen.set(v,row.__source_file)}}
function url(row,field){const value=row[field];if(!value)return;try{const parsed=new URL(value);if(!['http:','https:'].includes(parsed.protocol))failures.push(`${label(row)} ${field} must use http or https`)}catch{failures.push(`${label(row)} invalid ${field}: ${value}`)}}
const stablecoins=combine('stablecoins.json','stablecoins-extra.json','stablecoins-batch-b.json');
const organizations=combine('organizations.json','organizations-batch-b.json');
const relationships=combine('relationships.json','relationships-batch-b.json');
const legacyIssuers=combine('issuers.json','issuers-extra.json','issuers-batch-b.json');
const events=combine('events.json','events-pr036.json','events-pr037.json','events-pr038.json','events-batch-a.json','events-batch-b.json','events-issuer-control-2026.json');
const evidence=combine('evidence.json','evidence-extra.json','evidence-pr033.json','evidence-events-pr036.json','evidence-events-pr037.json','evidence-events-pr038.json','evidence-batch-a.json','evidence-batch-b.json','evidence-issuer-control-2026.json');
const reserveReports=combine('reserve-reports.json','reserve-reports-extra.json','reserve-reports-pr033.json','reserve-reports-pr034.json','reserve-reports-batch-b.json');
const knownUnknowns=combine('known-unknowns.json','known-unknowns-extra.json','known-unknowns-pr033.json','known-unknowns-pr034.json','known-unknowns-batch-a.json','known-unknowns-batch-b.json','known-unknowns-issuer-control-2026.json');
const regulatoryNotes=combine('regulatory-notes.json');
const deployments=combine('deployments.json','deployments-extra.json','deployments-batch-a.json','deployments-batch-b.json','deployments-issuer-control-2026.json');
for(const row of stablecoins){req(row,'id');req(row,'slug');req(row,'name');req(row,'status');req(row,'issuer_id')}unique('stablecoins',stablecoins,'id');unique('stablecoins',stablecoins,'slug');
for(const row of organizations){req(row,'id');req(row,'slug');req(row,'name');req(row,'organization_type');url(row,'official_url')}unique('organizations',organizations,'id');unique('organizations',organizations,'slug');
const organizationById=new Map(organizations.map((row)=>[row.id,row]));const legacyById=new Map(legacyIssuers.map((row)=>[row.id,row]));
for(const row of organizations){const legacy=legacyById.get(row.id);if(!legacy)failures.push(`${label(row)} has no legacy issuer compatibility record`);else if(legacy.slug!==row.slug)failures.push(`${label(row)} slug differs from legacy ${legacy.slug}`)}
for(const row of legacyIssuers)if(!organizationById.has(row.id))failures.push(`${label(row)} missing from organization groups`);
const stablecoinIds=new Set(stablecoins.map((row)=>row.id));const organizationIds=new Set(organizations.map((row)=>row.id));const eventIds=new Set(events.map((row)=>row.id));const evidenceIds=new Set(evidence.map((row)=>row.id));
for(const row of relationships){req(row,'id');req(row,'stablecoin_id');req(row,'organization_id');req(row,'role');if(!stablecoinIds.has(row.stablecoin_id))failures.push(`${label(row)} missing stablecoin ${row.stablecoin_id}`);if(!organizationIds.has(row.organization_id))failures.push(`${label(row)} missing organization ${row.organization_id}`);for(const id of row.evidence_ids??[])if(!evidenceIds.has(id))failures.push(`${label(row)} missing evidence ${id}`)}unique('relationships',relationships,'id');
const relByStablecoin=new Map();for(const row of relationships){const list=relByStablecoin.get(row.stablecoin_id)??[];list.push(row);relByStablecoin.set(row.stablecoin_id,list)}
for(const row of stablecoins){if(!organizationIds.has(row.issuer_id))failures.push(`${label(row)} missing organization ${row.issuer_id}`);const related=relByStablecoin.get(row.id)??[];if(!related.length)failures.push(`${label(row)} has no organization relationship`);if(!related.some((r)=>r.organization_id===row.issuer_id))failures.push(`${label(row)} issuer_id not represented in relationships`)}
for(const row of events){req(row,'id');req(row,'title');if(row.stablecoin_id&&!stablecoinIds.has(row.stablecoin_id))failures.push(`${label(row)} missing stablecoin ${row.stablecoin_id}`);if(row.issuer_id&&!organizationIds.has(row.issuer_id))failures.push(`${label(row)} missing organization ${row.issuer_id}`)}unique('events',events,'id');
for(const row of evidence){req(row,'id');req(row,'title');req(row,'url');url(row,'url');if(row.stablecoin_id&&!stablecoinIds.has(row.stablecoin_id))failures.push(`${label(row)} missing stablecoin ${row.stablecoin_id}`);if(row.issuer_id&&!organizationIds.has(row.issuer_id))failures.push(`${label(row)} missing organization ${row.issuer_id}`);if(row.event_id&&!eventIds.has(row.event_id))failures.push(`${label(row)} missing event ${row.event_id}`);for(const id of row.event_ids??[])if(!eventIds.has(id))failures.push(`${label(row)} missing event ${id}`)}unique('evidence',evidence,'id');
for(const row of reserveReports){req(row,'id');url(row,'url');if(row.stablecoin_id&&!stablecoinIds.has(row.stablecoin_id))failures.push(`${label(row)} missing stablecoin`);if(row.issuer_id&&!organizationIds.has(row.issuer_id))failures.push(`${label(row)} missing organization`)}unique('reserve reports',reserveReports,'id');
for(const row of knownUnknowns){req(row,'id');req(row,'topic');req(row,'description');if(row.stablecoin_id&&!stablecoinIds.has(row.stablecoin_id))failures.push(`${label(row)} missing stablecoin`);if(row.issuer_id&&!organizationIds.has(row.issuer_id))failures.push(`${label(row)} missing organization`)}unique('known unknowns',knownUnknowns,'id');
for(const row of regulatoryNotes){req(row,'id');req(row,'title');req(row,'summary');req(row,'source_url');url(row,'source_url');if(row.stablecoin_id&&!stablecoinIds.has(row.stablecoin_id))failures.push(`${label(row)} missing stablecoin`);if(row.issuer_id&&!organizationIds.has(row.issuer_id))failures.push(`${label(row)} missing organization`);if(row.event_id&&!eventIds.has(row.event_id))failures.push(`${label(row)} missing event`)}unique('regulatory notes',regulatoryNotes,'id');
for(const row of deployments){req(row,'id');req(row,'stablecoin_id');req(row,'chain');req(row,'deployment_type');req(row,'status');if(!stablecoinIds.has(row.stablecoin_id))failures.push(`${label(row)} missing stablecoin ${row.stablecoin_id}`);for(const id of row.evidence_ids??[])if(!evidenceIds.has(id))failures.push(`${label(row)} missing evidence ${id}`);for(const id of row.control_event_ids??[])if(!eventIds.has(id))failures.push(`${label(row)} missing control event ${id}`);if(row.freeze_capability!==undefined&&typeof row.freeze_capability!=='boolean')failures.push(`${label(row)} freeze_capability must be boolean`);if(row.blacklist_capability!==undefined&&typeof row.blacklist_capability!=='boolean')failures.push(`${label(row)} blacklist_capability must be boolean`)}unique('deployments',deployments,'id');
if(failures.length){console.error('SOG data validation failed:');failures.forEach((x)=>console.error(`- ${x}`));process.exit(1)}
console.log(`SOG data validation passed: ${stablecoins.length} stablecoins, ${organizations.length} organizations, ${relationships.length} relationships, ${events.length} events, ${evidence.length} evidence records, ${reserveReports.length} reserve references, ${knownUnknowns.length} known unknowns, ${regulatoryNotes.length} regulatory notes, ${deployments.length} deployments.`);
