import fs from 'node:fs';
import path from 'node:path';
import './validate-ui-v3-guides.mjs';

const root = process.cwd();
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const check = (condition, message) => { if (!condition) throw new Error(message); };

const datedGuideSlugs = ['genius-act-stablecoins', 'mica-stablecoins', 'jpyc-vs-jpysc', 'uk-stablecoin-capital-rules-2026', 'open-usd-reserve-revenue-model'];
const evergreenGuideSlugs = ['what-is-a-depeg', 'status-vs-event', 'reserve-disclosure-basics', 'stablecoin-lifecycle-terms'];
const catalog = read('src/data/guideCatalog.ts');
const slugs = catalog.split('\n').map((line) => line.trim()).filter((line) => line.startsWith("slug: '")).map((line) => line.slice(7).split("'")[0]).filter(Boolean);

check(slugs.length > 0, 'No guide slugs found in guideCatalog.ts');
check(new Set(slugs).size === slugs.length, 'Duplicate guide slug found');
check(catalog.includes('export function getPublishedGuides()'), 'Published-guide selector missing');
check(catalog.includes('export function getFeaturedGuides(limit = 3)'), 'Featured-guide selector missing');
check(catalog.includes("slug: 'uk-stablecoin-capital-rules-2026'"), 'UK guide catalog entry missing');
check(catalog.includes("publishedAt: '2026-06-30'"), 'UK guide publication date missing');
check(catalog.includes("regionLabel: 'United Kingdom'"), 'UK guide home metadata missing');
check(catalog.includes("slug: 'open-usd-reserve-revenue-model'"), 'Open USD guide catalog entry missing');
check(catalog.includes("informationCurrentThrough: '2026-07-01'"), 'Open USD information date was not updated');
check(catalog.includes("updatedAt: '2026-07-01'"), 'Open USD updated date missing');
check(catalog.includes('all reserve earnings after a small management fee'), 'Open USD catalog summary does not reflect the official earnings claim');
for (const slug of evergreenGuideSlugs) check(slugs.includes(slug), `Evergreen guide catalog entry missing: ${slug}`);

for (const slug of slugs) {
  const pagePath = `src/pages/guides/${slug}/index.astro`;
  check(fs.existsSync(path.join(root, pagePath)), `Missing guide page: ${pagePath}`);
  const page = read(pagePath);
  check(page.includes(`/guides/${slug}/`), `${pagePath}: canonical guide route missing`);
  check(page.includes(`getGuide('${slug}')`), `${pagePath}: guide catalog lookup mismatch`);
  check(page.includes('<GuideArticleHeader'), `${pagePath}: Editorial Article header missing`);
  if (!datedGuideSlugs.includes(slug)) continue;
  check(page.includes(`const canonicalPath = '/guides/${slug}/'`), `${pagePath}: dated-guide canonical path mismatch`);
  check(page.includes('<GuideRevisionHistory'), `${pagePath}: dated revision history missing`);
}

const openUsdPage = read('src/pages/guides/open-usd-reserve-revenue-model/index.astro');
check(openUsdPage.includes('https://twitter.com/openstandard/status/2071952870396580314'), 'Open USD official announcement URL missing');
check(openUsdPage.includes("partners will receive all earnings generated by the stablecoin's reserves after a small management fee"), 'Open USD official reserve-earnings statement missing');
check(openUsdPage.includes('with no artificial limit on volume'), 'Open USD no-artificial-volume-limit claim missing');
check(openUsdPage.includes('board will be made up of Open USD partners'), 'Open USD partner-board claim missing');
check(openUsdPage.includes('Stripe says Open USD will be the default stablecoin for businesses running on Stripe'), 'Open USD Stripe adoption statement missing');
check(openUsdPage.includes('not the same as announcing a finalized custody or banking role'), 'Open USD BNY role caveat missing');
check(openUsdPage.includes('No automatic holder-yield right'), 'Open USD holder-yield distinction missing');

const guideIndex = read('src/pages/guides/index.astro');
check(guideIndex.includes("import {\n  guides,"), 'Guides index must use the complete guide catalog');
check(guideIndex.includes('const visibleGuides = guides;'), 'Guides index must expose all public guide pages');
check(guideIndex.includes('visibleGuides.filter'), 'Guides index category filtering missing');
check(!guideIndex.includes('getPublishedGuides'), 'Guides index must not hide evergreen guides behind publication dates');
for (const slug of evergreenGuideSlugs) check(catalog.includes(`slug: '${slug}'`), `Evergreen guide is not represented in the visible catalog: ${slug}`);

const sitemap = read('src/pages/sitemap-index.xml.ts');
check(sitemap.includes("import { guides } from '../data/guideCatalog';"), 'Sitemap complete-guide import missing');
check(sitemap.includes('guides.map((guide) => `/guides/${guide.slug}/`)'), 'Sitemap must include every public guide route');
check(!sitemap.includes('getPublishedGuides'), 'Sitemap must not hide evergreen guide routes behind publication dates');

const home = read('src/pages/index.astro');
check(home.includes("import { getFeaturedGuides } from '../data/guideCatalog';"), 'Homepage featured-guide metadata import missing');
check(home.includes('getFeaturedGuides(4)'), 'Editorial Ledger Home must select the latest four featured guides automatically');
check(!home.includes("getGuide('genius-act-stablecoins')"), 'Homepage must not hard-code featured guide slugs');

const linkMap = read('src/data/stablecoinGuideLinks.ts');
for (const slug of datedGuideSlugs) check(linkMap.includes(`'${slug}': [`), `Stablecoin guide link map missing: ${slug}`);

const detail = read('src/components/StablecoinDetailView.astro');
const relatedSection = read('src/components/StablecoinRelatedSection.astro');
check(detail.includes('getRelatedGuidesForStablecoin'), 'Stablecoin detail related-guide lookup missing');
check(relatedSection.includes('<RelatedGuides guides={relatedGuides} />'), 'Stablecoin detail related-guide component missing');
check(detail.includes('subjectOf:'), 'Stablecoin detail guide metadata missing');

const updates = JSON.parse(read('data/registry-updates.json'));
const datedGuidesUpdate = updates.find((entry) => entry.id === 'sog_update_2026_06_25_pr129_pr132_dated_guides');
check(Boolean(datedGuidesUpdate), 'Original dated-guide update entry missing');
for (const slug of ['genius-act-stablecoins', 'mica-stablecoins', 'jpyc-vs-jpysc']) check(datedGuidesUpdate.related_paths.includes(`/guides/${slug}/`), `Original update route missing: ${slug}`);

console.log(JSON.stringify({ ok: true, guides: slugs.length, dated_guides: datedGuideSlugs.length, evergreen_guides: evergreenGuideSlugs.length, automatic_featured_guides: true, home_featured_guide_limit: 4, guide_slugs: slugs }, null, 2));
