import fs from 'node:fs';
import path from 'node:path';
import './validate-ui-v3-guides.mjs';
import './validate-ui-v3-reference-utility.mjs';

const root = process.cwd();
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const check = (condition, message) => { if (!condition) throw new Error(message); };

const datedGuideSlugs = ['eu-stablecoin-access-after-mica', 'genius-act-stablecoins', 'mica-stablecoins', 'jpyc-vs-jpysc', 'uk-stablecoin-capital-rules-2026', 'open-usd-reserve-revenue-model'];
const evergreenGuideSlugs = ['what-is-a-depeg', 'status-vs-event', 'reserve-disclosure-basics', 'stablecoin-lifecycle-terms'];
const catalog = read('src/data/guideCatalog.ts');
const slugs = catalog.split('\n').map((line) => line.trim()).filter((line) => line.startsWith("slug: '")).map((line) => line.slice(7).split("'")[0]).filter(Boolean);

check(slugs.length > 0, 'No guide slugs found in guideCatalog.ts');
check(new Set(slugs).size === slugs.length, 'Duplicate guide slug found');
check(catalog.includes('export function getPublishedGuides()'), 'Published-guide selector missing');
check(catalog.includes('export function getFeaturedGuides(limit = 3)'), 'Featured-guide selector missing');
check(catalog.includes("slug: 'uk-stablecoin-capital-rules-2026'"), 'UK guide catalog entry missing');
check(catalog.includes("publishedAt: '2026-06-30'"), 'UK guide publication date missing');
check(catalog.includes("regionLabel: 'United Kingdom'"), 'UK guide home metadata missing');
check(catalog.includes("slug: 'open-usd-reserve-revenue-model'"), 'Open USD guide catalog entry missing');
check(catalog.includes("informationCurrentThrough: '2026-07-01'"), 'Open USD information date was not updated');
check(catalog.includes("updatedAt: '2026-07-01'"), 'Open USD updated date missing');
check(catalog.includes('all reserve earnings after a small management fee'), 'Open USD catalog summary does not reflect the official earnings claim');
check(catalog.includes("slug: 'eu-stablecoin-access-after-mica'"), 'EU stablecoin access guide catalog entry missing');
check(catalog.includes("title: 'After MiCA: Which Stablecoins Can Europeans Actually Use?'"), 'EU stablecoin access guide title missing');
check(catalog.includes("publishedAt: '2026-07-05'"), 'EU stablecoin access guide publication date missing');
check(catalog.includes("informationCurrentThrough: '2026-07-05'"), 'EU stablecoin access guide information date missing');
check(catalog.includes("regionLabel: 'European Union / EEA'"), 'EU stablecoin access guide regional metadata missing');
for (const slug of evergreenGuideSlugs) check(slugs.includes(slug), `Evergreen guide catalog entry missing: ${slug}`);

for (const slug of slugs) {
  const pagePath = `src/pages/guides/${slug}/index.astro`;
  check(fs.existsSync(path.join(root, pagePath)), `Missing guide page: ${pagePath}`);
  const page = read(pagePath);
  check(page.includes(`/guides/${slug}/`), `${pagePath}: canonical guide route missing`);
  if (!datedGuideSlugs.includes(slug)) continue;
  check(page.includes(`getGuide('${slug}')`), `${pagePath}: dated-guide catalog lookup mismatch`);
  check(page.includes(`const canonicalPath = '/guides/${slug}/'`), `${pagePath}: dated-guide canonical path mismatch`);
  check(page.includes('<GuideArticleHeader'), `${pagePath}: dated article header missing`);
  check(page.includes('<GuideRevisionHistory'), `${pagePath}: dated revision history missing`);
}

const openUsdPage = read('src/pages/guides/open-usd-reserve-revenue-model/index.astro');
check(openUsdPage.includes('https://twitter.com/openstandard/status/2071952870396580314'), 'Open USD official announcement URL missing');
check(openUsdPage.includes("partners will receive all earnings generated by the stablecoin's reserves after a small management fee"), 'Open USD official reserve-earnings statement missing');
check(openUsdPage.includes('with no artificial limit on volume'), 'Open USD no-artificial-volume-limit claim missing');
check(openUsdPage.includes('board will be made up of Open USD partners'), 'Open USD partner-board claim missing');
check(openUsdPage.includes('Stripe says Open USD will be the default stablecoin for businesses running on Stripe'), 'Open USD Stripe adoption statement missing');
check(openUsdPage.includes('not the same as announcing a finalized custody or banking role'), 'Open USD BNY role caveat missing');
check(openUsdPage.includes('No automatic holder-yield right'), 'Open USD holder-yield distinction missing');

const euAccessPage = read('src/pages/guides/eu-stablecoin-access-after-mica/index.astro');
const euAccessGateReview = read('docs/audits/eu-stablecoin-market-access-publication-gate-review-2026-07-05.md');
const euAccessReaudit = read('docs/audits/eu-stablecoin-market-access-prepublication-reaudit-2026-07-05.md');
const euAccessFunctionBatch = JSON.parse(read('data/editorial-research/eu-stablecoin-market-access-function-batch-03.json'));
const euAccessReauditBatch = JSON.parse(read('data/editorial-research/eu-stablecoin-market-access-reaudit-batch-04.json'));
check(euAccessGateReview.includes('publication gate:                               pass'), 'EU market access publication gate was not recorded as passed');
check(euAccessGateReview.includes('A. Asset-specific function evidence'), 'EU market access gate review missing A-level evidence contract');
check(euAccessGateReview.includes('B. Current platform-wide service-state evidence'), 'EU market access gate review missing B-level evidence contract');
check(euAccessGateReview.includes('C. General service/licensing context'), 'EU market access gate review missing C-level evidence contract');
check(euAccessFunctionBatch.gate_effect?.publication_ready === false, 'Checkpoint 03 source batch must remain a research checkpoint rather than self-authorizing publication');
check(euAccessReaudit.includes('article revision from re-audit: complete'), 'EU market access reaudit must record article revision completion');
check(euAccessReaudit.includes('merge authorized: no'), 'EU market access reaudit must preserve human merge gate');
check(euAccessReauditBatch.article_gate_effect?.full_asset_and_platform_reaudit_complete === true, 'EU market access batch 04 reaudit completion missing');
check(euAccessReauditBatch.article_gate_effect?.article_requires_additional_revision === true, 'Batch 04 must preserve its original finding that article revision was required');
check(euAccessPage.includes('This guide is a reviewed snapshot current through July 5, 2026.'), 'EU market access guide snapshot date missing');
check(euAccessPage.includes('/guides/mica-stablecoins/'), 'EU market access guide must link to the MiCA framework guide');
check(euAccessPage.includes('Reporting based on a customer notice said Revolut would phase out USDT support.'), 'EU market access guide must preserve conservative reported Revolut treatment');
check(euAccessPage.includes('Reviewed asset-specific function examples'), 'EU market access guide A-level comparison section missing');
check(euAccessPage.includes('Platform state and product surfaces are different evidence layers'), 'EU market access guide bounded platform-context section missing');
check(euAccessPage.includes('RLUSD: one asset, four separate layers'), 'EU market access guide RLUSD four-layer correction missing');
check(euAccessPage.includes('product surfaces, not proof of uniform EEA-wide asset availability'), 'EU market access guide OKX scope downgrade missing');
check(euAccessPage.includes('Paxos Issuance Europe under FIN-FSA supervision'), 'EU market access guide USDG European issuance path missing');
check(euAccessPage.includes('Redemption-Only Mode'), 'EU market access guide EUROe redemption-only context missing');
check(euAccessPage.includes('EURAU'), 'EU market access guide EURAU bounded example missing');
check(euAccessPage.includes('EUROD'), 'EU market access guide EUROD bounded example missing');
check(euAccessPage.includes('does not issue any stablecoins or tokens yet'), 'EU market access guide Qivalis future-only boundary missing');
check(euAccessPage.includes('At least eight layers can move independently'), 'EU market access guide eight-layer framework missing');
check(euAccessPage.includes('payment-services authorization layer'), 'EU market access guide payment-services layer missing');
for (const url of [
  'https://www.esma.europa.eu/esmas-activities/digital-finance-and-innovation/markets-crypto-assets-regulation-mica',
  'https://www.binance.com/en/support/announcement/detail/bcaa1f68d6a6450099056ff694ad6c46',
  'https://support.kraken.com/articles/stablecoin-offerings-for-eea-clients',
  'https://blog.bitstamp.net/post/mica-regulation-update-on-select-assets-in-the-eueea/',
  'https://www.okx.com/en-eu/buy-usdt',
  'https://www.okx.com/en-eu/buy-usdc',
  'https://crypto.com/eea',
  'https://www.bybit.eu/en-EU/help-center/article/Everything-You-Need-to-Know-to-Get-Started-on-Bybit',
  'https://support.gemini.com/hc/en-gb',
  'https://uphold.com/en-eu',
  'https://www.coinbase.com/en-de/price/tether',
  'https://www.coinbase.com/en-de/price/dai',
  'https://www.coinbase.com/en-de/price/paypal-usd',
  'https://ripple.com/ripple-press/ripple-receives-full-eu-electronic-money-institution-license-in-luxembourg/',
  'https://ripple.com/ripple-press/ripple-secures-preliminary-MiCA-CASP-license/',
  'https://ripple.com/legal/stablecoin/',
  'https://www.paxos.com/eu',
  'https://globaldollar.com/',
  'https://allunity.com/',
  'https://www.oddo-bhf.com/eurod-stablecoin/',
  'https://qivalis.eu/',
  'https://sky.money/'
]) check(euAccessPage.includes(url), `EU market access guide missing reviewed source URL: ${url}`);

const guideIndexRoute = read('src/pages/guides/index.astro');
const guideIndex = read('src/components/GuideEditorialIndex.astro');
check(guideIndexRoute.includes('GuideEditorialIndex'), 'Guides route must use GuideEditorialIndex');
check(guideIndex.includes("import { guides, guideCategoryDescriptions, guideCategoryLabels"), 'Guide index must use the complete guide catalog');
check(guideIndex.includes('guides.filter'), 'Guide index category filtering missing');
check(!guideIndex.includes('getPublishedGuides'), 'Guide index must not hide evergreen guides behind publication dates');
for (const slug of evergreenGuideSlugs) check(catalog.includes(`slug: '${slug}'`), `Evergreen guide is not represented in the visible catalog: ${slug}`);

const sitemap = read('src/pages/sitemap-index.xml.ts');
check(sitemap.includes("import { guides } from '../data/guideCatalog';"), 'Sitemap complete-guide import missing');
check(sitemap.includes('guides.map((guide) => `/guides/${guide.slug}/`)'), 'Sitemap must include every public guide route');
check(!sitemap.includes('getPublishedGuides'), 'Sitemap must not hide evergreen guide routes behind publication dates');

const home = read('src/pages/index.astro');
check(home.includes("import { getFeaturedGuides } from '../data/guideCatalog';"), 'Homepage featured-guide metadata import missing');
check(home.includes('getFeaturedGuides(4)'), 'Editorial Ledger Home must select the latest four featured guides automatically');
check(!home.includes("getGuide('genius-act-stablecoins')"), 'Homepage must not hard-code featured guide slugs');

const linkMap = read('src/data/stablecoinGuideLinks.ts');
for (const slug of datedGuideSlugs) check(linkMap.includes(`'${slug}': [`), `Stablecoin guide link map missing: ${slug}`);
for (const stablecoinSlug of ['usdt', 'usdc', 'eurc', 'dai', 'pyusd', 'rlusd', 'euri', 'eurcv', 'eurq', 'usdq', 'usdg']) check(linkMap.includes(`'${stablecoinSlug}'`) || linkMap.includes(`'${stablecoinSlug}',`) || linkMap.includes(`, '${stablecoinSlug}'`), `EU market access guide link coverage missing: ${stablecoinSlug}`);

const detail = read('src/components/StablecoinDetailView.astro');
const relatedSection = read('src/components/StablecoinRelatedSection.astro');
check(detail.includes('getRelatedGuidesForStablecoin'), 'Stablecoin detail related-guide lookup missing');
check(relatedSection.includes('<RelatedGuides guides={relatedGuides} />'), 'Stablecoin detail related-guide component missing');
check(detail.includes('subjectOf:'), 'Stablecoin detail guide metadata missing');

const updates = JSON.parse(read('data/registry-updates.json'));
const datedGuidesUpdate = updates.find((entry) => entry.id === 'sog_update_2026_06_25_pr129_pr132_dated_guides');
check(Boolean(datedGuidesUpdate), 'Original dated-guide update entry missing');
for (const slug of ['genius-act-stablecoins', 'mica-stablecoins', 'jpyc-vs-jpysc']) check(datedGuidesUpdate.related_paths.includes(`/guides/${slug}/`), `Original update route missing: ${slug}`);
const euAccessUpdate = updates.find((entry) => entry.id === 'sog_update_2026_07_05_eu_stablecoin_access_guide');
check(Boolean(euAccessUpdate), 'EU stablecoin access guide registry update entry missing');
check(euAccessUpdate.related_paths.includes('/guides/eu-stablecoin-access-after-mica/'), 'EU stablecoin access guide update route missing');

console.log(JSON.stringify({ ok: true, guides: slugs.length, dated_guides: datedGuideSlugs.length, evergreen_guides: evergreenGuideSlugs.length, automatic_featured_guides: true, home_featured_guide_limit: 4, editorial_article_v3: true, reference_utility_v3: true, eu_market_access_gate_reviewed: true, eu_market_access_reaudit_applied: true, guide_slugs: slugs }, null, 2));
